version: '3'
services:
  pooling:
    image: car-pooling:latest
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
  harness:
    image: cabify/challenge:latest
    command: /harness --address http://pooling:8080 acceptance
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest